In [4]:
import pandas as pd 
df = pd.read_csv("C:/Users/PC/Downloads/jupiter/Supply_Chain_and risk_performance.csv")

In [5]:
df.head()

,Order_ID,Buyer_ID,Supplier_ID,Product_Category,Quantity_Ordered,Order_Date,Dispatch_Date,Delivery_Date,Shipping_Mode,Order_Value_USD,...,Supplier_Reliability_Score,Organization_ID,Dominant_Buyer_Flag,Available_Historical_Records,Data_Sharing_Consent,Federated_Round,Parameter_Change_Magnitude,Communication_Cost_MB,Energy_Consumption_Joules,Supply_Risk_Flag
0,O1000,B33,S23,Textiles,469,2023-10-24,2023-10-27,2023-10-28,Rail,36273.99,...,0.73,Org13,0,127,1,10,0.0225,2.27,236.06,0
1,O1001,B1,S20,Machinery,365,2023-07-07,2023-07-08,2023-07-09,Road,34780.36,...,0.88,Org8,1,909,1,7,0.0412,3.10,257.80,0
2,O1002,B2,S10,Food,333,2023-12-28,2023-12-29,2024-01-07,Rail,7154.54,...,0.95,Org4,0,262,1,8,0.1183,2.82,165.38,1
3,O1003,B6,S10,Machinery,142,2023-01-14,2023-01-17,2023-01-20,Rail,15320.08,...,0.92,Org18,1,807,1,9,0.2611,3.59,377.47,0
4,O1004,B5,S4,Machinery,897,2023-01-12,2023-01-14,2023-01-16,Road,18256.42,...,0.60,Org13,0,789,1,7,0.2775,3.42,83.10,0

In [6]:
df.shape

(1000, 24)

In [7]:
df.info

<bound method DataFrame.info of     Order_ID Buyer_ID Supplier_ID Product_Category  Quantity_Ordered  \
0      O1000      B33         S23         Textiles               469
1      O1001       B1         S20        Machinery               365
2      O1002       B2         S10             Food               333
3      O1003       B6         S10        Machinery               142
4      O1004       B5          S4        Machinery               897
..       ...      ...         ...              ...               ...
995    O1995      B23         S27           Pharma                31
996    O1996      B45          S2      Electronics               419
997    O1997      B22         S24      Electronics               904
998    O1998      B10         S26         Textiles               524
999    O1999       B4          S9             Food               136

     Order_Date Dispatch_Date Delivery_Date Shipping_Mode  Order_Value_USD  \
0    2023-10-24    2023-10-27    2023-10-28          Rail         36273.99
1    2023-07-07    2023-07-08    2023-07-09          Road         34780.36
2    2023-12-28    2023-12-29    2024-01-07          Rail          7154.54
3    2023-01-14    2023-01-17    2023-01-20          Rail         15320.08
4    2023-01-12    2023-01-14    2023-01-16          Road         18256.42
..          ...           ...           ...           ...              ...
995  2023-06-27    2023-07-01    2023-07-10           Sea         42701.10
996  2023-01-07    2023-01-10    2023-01-19          Rail         46929.28
997  2023-03-11    2023-03-13    2023-03-16           Sea          4712.62
998  2023-05-07    2023-05-10    2023-05-18           Air         19587.08
999  2023-06-09    2023-06-10    2023-06-18           Sea          4016.23

     ...  Supplier_Reliability_Score Organization_ID Dominant_Buyer_Flag  \
0    ...                        0.73           Org13                   0
1    ...                        0.88            Org8                   1
2    ...                        0.95            Org4                   0
3    ...                        0.92           Org18                   1
4    ...                        0.60           Org13                   0
..   ...                         ...             ...                 ...
995  ...                        0.93            Org9                   0
996  ...                        0.74           Org20                   0
997  ...                        0.86           Org15                   0
998  ...                        0.70            Org4                   0
999  ...                        0.63            Org4                   0

     Available_Historical_Records  Data_Sharing_Consent Federated_Round  \
0                             127                     1              10
1                             909                     1               7
2                             262                     1               8
3                             807                     1               9
4                             789                     1               7
..                            ...                   ...             ...
995                           518                     1              10
996                           188                     1               3
997                           762                     1               6
998                           847                     1               7
999                           840                     0               7

     Parameter_Change_Magnitude  Communication_Cost_MB  \
0                        0.0225                   2.27
1                        0.0412                   3.10
2                        0.1183                   2.82
3                        0.2611                   3.59
4                        0.2775                   3.42
..                          ...                    ...
995                      0.3041                   3.70
996                      0.0678                   2.40
997                      0.0376                   3.43
998                      0.2119                   1.67
999                      0.2937                   0.81

     Energy_Consumption_Joules  Supply_Risk_Flag
0                       236.06                 0
1                       257.80                 0
2                       165.38                 1
3                       377.47                 0
4                        83.10                 0
..                         ...               ...
995                     147.10                 1
996                      69.62                 1
997                     187.43                 0
998                     363.11                 0
999                     478.00                 0

[1000 rows x 24 columns]>

In [8]:
df.describe()

,Quantity_Ordered,Order_Value_USD,Delay_Days,Historical_Disruption_Count,Supplier_Reliability_Score,Dominant_Buyer_Flag,Available_Historical_Records,Data_Sharing_Consent,Federated_Round,Parameter_Change_Magnitude,Communication_Cost_MB,Energy_Consumption_Joules,Supply_Risk_Flag
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,504.288000,25290.073670,1.943000,9.841000,0.745760,0.286000,510.317000,0.805000,5.67900,0.251096,2.768760,270.855090,0.514000
std,295.545455,14380.329641,2.852699,5.656652,0.143063,0.452115,281.700777,0.396399,2.86499,0.139568,1.275225,130.218495,0.500054
min,10.000000,500.580000,0.000000,0.000000,0.500000,0.000000,10.000000,0.000000,1.00000,0.011300,0.500000,50.490000,0.000000
25%,248.000000,12891.837500,0.000000,5.000000,0.620000,0.000000,262.750000,1.000000,3.00000,0.131975,1.740000,163.597500,0.000000
50%,499.000000,25596.005000,1.000000,10.000000,0.740000,0.000000,521.500000,1.000000,6.00000,0.255050,2.760000,268.370000,1.000000
75%,760.500000,37574.430000,3.000000,15.000000,0.870000,1.000000,752.000000,1.000000,8.00000,0.369550,3.822500,383.835000,1.000000
max,999.000000,49945.180000,10.000000,19.000000,1.000000,1.000000,998.000000,1.000000,10.00000,0.499800,5.000000,499.840000,1.000000

In [9]:
df["Delay_Days"].describe()

count    1000.000000
mean        1.943000
std         2.852699
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        10.000000
Name: Delay_Days, dtype: float64

In [10]:
df.isnull().sum()

Order_ID                          0
Buyer_ID                          0
Supplier_ID                       0
Product_Category                  0
Quantity_Ordered                  0
Order_Date                        0
Dispatch_Date                     0
Delivery_Date                     0
Shipping_Mode                     0
Order_Value_USD                   0
Delay_Days                        0
Disruption_Type                 486
Disruption_Severity             486
Historical_Disruption_Count       0
Supplier_Reliability_Score        0
Organization_ID                   0
Dominant_Buyer_Flag               0
Available_Historical_Records      0
Data_Sharing_Consent              0
Federated_Round                   0
Parameter_Change_Magnitude        0
Communication_Cost_MB             0
Energy_Consumption_Joules         0
Supply_Risk_Flag                  0
dtype: int64

In [11]:
df[" Disruption_Type"]= df["Disruption_Type"].fillna("No Disruption")

In [12]:
df.columns

Index(['Order_ID', 'Buyer_ID', 'Supplier_ID', 'Product_Category',
       'Quantity_Ordered', 'Order_Date', 'Dispatch_Date', 'Delivery_Date',
       'Shipping_Mode', 'Order_Value_USD', 'Delay_Days', 'Disruption_Type',
       'Disruption_Severity', 'Historical_Disruption_Count',
       'Supplier_Reliability_Score', 'Organization_ID', 'Dominant_Buyer_Flag',
       'Available_Historical_Records', 'Data_Sharing_Consent',
       'Federated_Round', 'Parameter_Change_Magnitude',
       'Communication_Cost_MB', 'Energy_Consumption_Joules',
       'Supply_Risk_Flag', ' Disruption_Type'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Order_ID                      1000 non-null   object
 1   Buyer_ID                      1000 non-null   object
 2   Supplier_ID                   1000 non-null   object
 3   Product_Category              1000 non-null   object
 4   Quantity_Ordered              1000 non-null   int64
 5   Order_Date                    1000 non-null   object
 6   Dispatch_Date                 1000 non-null   object
 7   Delivery_Date                 1000 non-null   object
 8   Shipping_Mode                 1000 non-null   object
 9   Order_Value_USD               1000 non-null   float64
 10  Delay_Days                    1000 non-null   int64
 11  Disruption_Type               514 non-null    object
 12  Disruption_Severity           514 non-null    object
 13  Historical_Disruption_Count   1000 non-null   int64
 14  Supplier_Reliability_Score    1000 non-null   float64
 15  Organization_ID               1000 non-null   object
 16  Dominant_Buyer_Flag           1000 non-null   int64
 17  Available_Historical_Records  1000 non-null   int64
 18  Data_Sharing_Consent          1000 non-null   int64
 19  Federated_Round               1000 non-null   int64
 20  Parameter_Change_Magnitude    1000 non-null   float64
 21  Communication_Cost_MB         1000 non-null   float64
 22  Energy_Consumption_Joules     1000 non-null   float64
 23  Supply_Risk_Flag              1000 non-null   int64
 24   Disruption_Type              1000 non-null   object
dtypes: float64(5), int64(8), object(12)
memory usage: 195.4+ KB

In [14]:
df.isnull().sum()

Order_ID                          0
Buyer_ID                          0
Supplier_ID                       0
Product_Category                  0
Quantity_Ordered                  0
Order_Date                        0
Dispatch_Date                     0
Delivery_Date                     0
Shipping_Mode                     0
Order_Value_USD                   0
Delay_Days                        0
Disruption_Type                 486
Disruption_Severity             486
Historical_Disruption_Count       0
Supplier_Reliability_Score        0
Organization_ID                   0
Dominant_Buyer_Flag               0
Available_Historical_Records      0
Data_Sharing_Consent              0
Federated_Round                   0
Parameter_Change_Magnitude        0
Communication_Cost_MB             0
Energy_Consumption_Joules         0
Supply_Risk_Flag                  0
 Disruption_Type                  0
dtype: int64

In [15]:
df["Disruption_Type"]=df["Disruption_Type"].fillna("No Disruption")
df["Disruption_Severity"]=df["Disruption_Severity"].fillna("No Impact")

In [16]:
df.isnull().sum()

Order_ID                        0
Buyer_ID                        0
Supplier_ID                     0
Product_Category                0
Quantity_Ordered                0
Order_Date                      0
Dispatch_Date                   0
Delivery_Date                   0
Shipping_Mode                   0
Order_Value_USD                 0
Delay_Days                      0
Disruption_Type                 0
Disruption_Severity             0
Historical_Disruption_Count     0
Supplier_Reliability_Score      0
Organization_ID                 0
Dominant_Buyer_Flag             0
Available_Historical_Records    0
Data_Sharing_Consent            0
Federated_Round                 0
Parameter_Change_Magnitude      0
Communication_Cost_MB           0
Energy_Consumption_Joules       0
Supply_Risk_Flag                0
 Disruption_Type                0
dtype: int64

In [17]:
df= df.drop(columns = ["Organization_ID","Available_Historical_Records","Data_Sharing_Consent","Federated_Round","Parameter_Change_Magnitude",])

In [18]:
df.columns

Index(['Order_ID', 'Buyer_ID', 'Supplier_ID', 'Product_Category',
       'Quantity_Ordered', 'Order_Date', 'Dispatch_Date', 'Delivery_Date',
       'Shipping_Mode', 'Order_Value_USD', 'Delay_Days', 'Disruption_Type',
       'Disruption_Severity', 'Historical_Disruption_Count',
       'Supplier_Reliability_Score', 'Dominant_Buyer_Flag',
       'Communication_Cost_MB', 'Energy_Consumption_Joules',
       'Supply_Risk_Flag', ' Disruption_Type'],
      dtype='object')

In [19]:
df.shape

(1000, 20)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.columns = df. columns.str.strip()

In [22]:
df.columns = df.columns.str.lower()

In [23]:
df= df.loc[:, ~df.columns.duplicated()]

In [24]:
df.dtypes

order_id                        object
buyer_id                        object
supplier_id                     object
product_category                object
quantity_ordered                 int64
order_date                      object
dispatch_date                   object
delivery_date                   object
shipping_mode                   object
order_value_usd                float64
delay_days                       int64
disruption_type                 object
disruption_severity             object
historical_disruption_count      int64
supplier_reliability_score     float64
dominant_buyer_flag              int64
communication_cost_mb          float64
energy_consumption_joules      float64
supply_risk_flag                 int64
dtype: object

In [25]:
date_cols=["order_date","dispatch_date","delivery_date"]
df[date_cols]= df[date_cols].apply(pd.to_datetime)

In [26]:
df.dtypes

order_id                               object
buyer_id                               object
supplier_id                            object
product_category                       object
quantity_ordered                        int64
order_date                     datetime64[ns]
dispatch_date                  datetime64[ns]
delivery_date                  datetime64[ns]
shipping_mode                          object
order_value_usd                       float64
delay_days                              int64
disruption_type                        object
disruption_severity                    object
historical_disruption_count             int64
supplier_reliability_score            float64
dominant_buyer_flag                     int64
communication_cost_mb                 float64
energy_consumption_joules             float64
supply_risk_flag                        int64
dtype: object

In [27]:
df[ df["delivery_date"]< df["order_date"]]

Empty DataFrame
Columns: [order_id, buyer_id, supplier_id, product_category, quantity_ordered, order_date, dispatch_date, delivery_date, shipping_mode, order_value_usd, delay_days, disruption_type, disruption_severity, historical_disruption_count, supplier_reliability_score, dominant_buyer_flag, communication_cost_mb, energy_consumption_joules, supply_risk_flag]
Index: []

In [28]:
df[df["delay_days"]<0]

Empty DataFrame
Columns: [order_id, buyer_id, supplier_id, product_category, quantity_ordered, order_date, dispatch_date, delivery_date, shipping_mode, order_value_usd, delay_days, disruption_type, disruption_severity, historical_disruption_count, supplier_reliability_score, dominant_buyer_flag, communication_cost_mb, energy_consumption_joules, supply_risk_flag]
Index: []

In [29]:
df[df["quantity_ordered"]<=0]

Empty DataFrame
Columns: [order_id, buyer_id, supplier_id, product_category, quantity_ordered, order_date, dispatch_date, delivery_date, shipping_mode, order_value_usd, delay_days, disruption_type, disruption_severity, historical_disruption_count, supplier_reliability_score, dominant_buyer_flag, communication_cost_mb, energy_consumption_joules, supply_risk_flag]
Index: []

In [30]:
df['dispatch_time']= (df['dispatch_date']-df['order_date']).dt.days ##Delivery Performance
df['delivery_time']=(df['delivery_date']-df['dispatch_date']).dt.days ##shippment effienecy
df['total_fullfilment_time']=(df['delivery_date']-df['order_date']).dt.days ## delay analysis

In [31]:
df.head()

,order_id,buyer_id,supplier_id,product_category,quantity_ordered,order_date,dispatch_date,delivery_date,shipping_mode,order_value_usd,...,disruption_severity,historical_disruption_count,supplier_reliability_score,dominant_buyer_flag,communication_cost_mb,energy_consumption_joules,supply_risk_flag,dispatch_time,delivery_time,total_fullfilment_time
0,O1000,B33,S23,Textiles,469,2023-10-24,2023-10-27,2023-10-28,Rail,36273.99,...,No Impact,11,0.73,0,2.27,236.06,0,3,1,4
1,O1001,B1,S20,Machinery,365,2023-07-07,2023-07-08,2023-07-09,Road,34780.36,...,No Impact,1,0.88,1,3.10,257.80,0,1,1,2
2,O1002,B2,S10,Food,333,2023-12-28,2023-12-29,2024-01-07,Rail,7154.54,...,Low,19,0.95,0,2.82,165.38,1,1,9,10
3,O1003,B6,S10,Machinery,142,2023-01-14,2023-01-17,2023-01-20,Rail,15320.08,...,No Impact,17,0.92,1,3.59,377.47,0,3,3,6
4,O1004,B5,S4,Machinery,897,2023-01-12,2023-01-14,2023-01-16,Road,18256.42,...,No Impact,5,0.60,0,3.42,83.10,0,2,2,4

In [32]:
pip install psycopg2 sqlalchemy

Requirement already satisfied: psycopg2 in c:\users\pc\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\pc\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\pc\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pc\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import pandas as pd
from sqlalchemy import create_engine

In [34]:
engine = create_engine(
"postgresql://postgres:admin123@localhost:5432/Supply_chain_db"
)

In [35]:
print(df.shape)

(1000, 22)

In [36]:
type(df)

pandas.core.frame.DataFrame

In [40]:
df.to_sql(
"supply_chain",
engine,
if_exists="replace",
index=False
)

1000

In [42]:
df.to_csv("final_supply_chain.csv", index=False)

In [43]:
whos

Variable               Type         Data/Info
---------------------------------------------
create_engine          function     <function create_engine at 0x000001A4240F1620>
dataframe_columns      function     <function dataframe_colum<...>ns at 0x000001A42375F920>
dataframe_hash         function     <function dataframe_hash at 0x000001A42375F2E0>
date_cols              list         n=3
df                     DataFrame    Shape: (1000, 22)
dtypes_str             function     <function dtypes_str at 0x000001A42375E5C0>
engine                 Engine       Engine(postgresql://postg<...>ost:5432/Supply_chain_db)
get_dataframes         function     <function get_dataframes at 0x000001A42375F9C0>
getpass                module       <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                module       <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
import_pandas_safely   function     <function import_pandas_s<...>ly at 0x000001A424356A20>
is_data_frame          function     <function is_data_frame at 0x000001A424356CA0>
json                   module       <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
pd                     module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>

In [46]:
df.to_csv(
"final_supply_chain.csv",
index=False
)

In [45]:
import os

print(os.listdir())

['.anaconda', '.cache', '.conda', '.continuum', '.docker', '.ipynb_checkpoints', '.ipython', '.jupyter', '.ms-ad', '.n8n', '.ollama', '3D Objects', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Customer_shopping_behavior.ipynb', 'Customer_Shopping_Behavior_Analysis.ipynb', 'Documents', 'Downloads', 'edb_pgbouncer.exe', 'Favorites', 'final_supply_chain.csv', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'n8n', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{e5196647-e22e-11ee-b534-283926191a07}.TM.blf', 'NTUSER.DAT{e5196647-e22e-11ee-b534-283926191a07}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{e5196647-e22e-11ee-b534-283926191a07}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'postgresql_13.exe', 'postgresql_17.exe', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'shopping_behavior_updated (1).csv', 'Start Menu', 'Supply_Chain and Risk .ipynb', 'Templates', 'Tracing', 'Untitled.ipynb', 'Videos']